Repository Divyammmmmm/hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#8 hacktoberfest
  multiply_two_polynomials.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#5 Create ChoosingProblems.cpp
  ChoosingProblems.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#6 Add solutions (C++)
  codechef/.DS_Store
  codechef/cpp/ElectionsInChefland.cpp
  codechef/cpp/HowMuchScholarship.cpp
  codechef/cpp/WeightBalance.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#11 merge sort
  mergesort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#16 it is basically kadane algo
  largest_sum_subarray.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#14 circular queue
  circularqueue.c
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#15 Updated contributors.md
  contributors.md
Labels: invalid

#13 Create Largest Sum Contiguous Subarray.cpp
  Largest Sum Contiguous Subarray.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#18 Create bubble_sort.cpp
  bubble_sort.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#12 Create heap-sort.cpp
  heap-sort.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#20 Patch 2
  myFolder/a.cpp
  myFolder/bintodec.cpp
  myFolder/slidingwindow.cpp
  myFolder/string.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#21 Create bintodec.cpp
  bintodec.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#22 Create fibonucci.cpp
  fibonucci.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#23 Create mcm.cpp
  mcm.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#26 Create radix.cpp
  radix.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
